### ISSUE TITLE
请教，如何配置的

### ISSUE THREAD

**Issue by Changzw** [RiseYellow/opengl_mac_vscode_env_test#1]
请问下，mac vscode 配置 opengl 有没有想过文档，主要是编译配置过程

**Comment by Changzw** [comment]
请教下，自己是第一使用 vscode 配置，需要看哪些资料

**Comment by RiseYellow** [comment]
1.安装cmke

2.下载glew源码http://glew.sourceforge.net/
sudo make install
默认install路径/usr/local/include

3.下载glfw源码
https://www.glfw.org/download.html
cmake .. -DGLFW_INSTALL=ON -DGLFW_BUILD_TESTS=ON  -DGLFW_BUILD_EXAMPLES=ON -DGLFW_BUILD_DOCS=ON
sudo make 
sudo make install
默认install路径/usr/local/include

找了下之前的笔记，希望对你有帮助
